[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.24"
evm_version = "shanghai"

optimizer = true
optimizer_runs = 9_999_999

[profile.via-ir]
via_ir = true

[fmt]
line_length = 100

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[polygonscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}" }

